title: widepeepoHappy
theme: minima
author: cangnidepigu
email: nokaki99@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am in the middle of carrying a League of Legends game about to close it out,
  and my bra-less wife brings me a sandwich (not asked for) with chips as I get 
  a double kill bot lane.

# social links
twitter_username: nxkaki 
github_username:  cangnidepigu # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
